---
- name: Template nginx.repo
  template: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo mode=0644

- name: install Nginx
  yum: pkg={{ item }} state=installed enablerepo=nginx
  with_items:
    - nginx
  notify: start nginx

- name: config nginx
  lineinfile:
    dest=/etc/nginx/nginx.conf
    regexp="^\\s+worker_connections "
    line="    worker_connections  {{worker_connections}};"
  notify: reload nginx

